# Generated by Django 6.0.2 on 2026-03-03 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('violence', 'Violence Detection'), ('hand_sos', 'Hand SOS'), ('severity', 'Incident Severity'), ('lost_child', 'Lost Child')], max_length=20)),
                ('severity', models.CharField(blank=True, default='', max_length=20)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('camera_room', models.CharField(blank=True, default='', max_length=100)),
                ('raw_payload', models.JSONField(default=dict)),
                ('thumbnail_b64', models.TextField(blank=True, default='')),
                ('is_alerted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
    ]
