# Generated by Django 6.0.2 on 2026-03-03 11:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipients', models.JSONField(default=list)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('image_filename', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('violence', 'Violence Detection'), ('hand_sos', 'Hand SOS'), ('severity', 'Incident Severity'), ('lost_child', 'Lost Child')], max_length=20)),
                ('severity', models.CharField(blank=True, default='', max_length=20)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('camera_room', models.CharField(blank=True, default='', max_length=100)),
                ('raw_payload', models.JSONField(default=dict)),
                ('thumbnail_b64', models.TextField(blank=True, default='')),
                ('is_alerted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='MissingPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('photo', models.ImageField(upload_to='missing_persons/')),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('is_found', models.BooleanField(default=False)),
                ('found_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='MLServiceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.CharField(help_text='http://ml_service:8001', max_length=255, verbose_name='ML Service Base URL')),
                ('timeout_seconds', models.PositiveIntegerField(default=10)),
                ('violence_enabled', models.BooleanField(default=True)),
                ('hand_sos_enabled', models.BooleanField(default=True)),
                ('severity_enabled', models.BooleanField(default=True)),
                ('sos_enabled', models.BooleanField(default=True)),
                ('lost_child_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ML Service Config',
                'verbose_name_plural': 'ML Service Config',
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrgRegistrationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('organisation_name', models.CharField(help_text='Pre-filled hint for the organisation name', max_length=255)),
                ('used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
    ]
