# Generated by Django 6.0.2 on 2026-03-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_incident_description_missingperson_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='severity',
            field=models.CharField(blank=True, choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Information')], default='low', max_length=20),
        ),
    ]
