# Generated by Django 6.0.2 on 2026-03-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_incident_severity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgregistrationtoken',
            name='expires_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
