# Generated by Django 6.0.2 on 2026-03-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_orgregistrationtoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgregistrationtoken',
            name='organisation_name',
            field=models.CharField(blank=True, help_text='Optional hint for the organisation name', max_length=255, null=True),
        ),
    ]
