# Generated by Django 6.0.2 on 2026-03-03 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_orgregistrationtoken_organisation_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('camera_type', models.CharField(choices=[('LOCAL', 'Laptop Camera'), ('REMOTE', 'Remote Stream (RTSP/HTTP)')], default='LOCAL', max_length=10)),
                ('stream_url', models.CharField(blank=True, help_text='RTSP or HTTP URL for remote streams', max_length=1024, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera_streams', to='api.organisation')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
