# Generated by Django 6.0.2 on 2026-03-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_camerastream'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mlserviceconfig',
            options={'ordering': ['-is_active', '-updated_at'], 'verbose_name': 'ML Service Config', 'verbose_name_plural': 'ML Service Configs'},
        ),
        migrations.AddField(
            model_name='mlserviceconfig',
            name='hand_sos_path',
            field=models.CharField(default='/api/hand_sos/detect', max_length=100),
        ),
        migrations.AddField(
            model_name='mlserviceconfig',
            name='health_path',
            field=models.CharField(default='/health', max_length=100),
        ),
        migrations.AddField(
            model_name='mlserviceconfig',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this the active configuration?'),
        ),
        migrations.AddField(
            model_name='mlserviceconfig',
            name='lost_child_path',
            field=models.CharField(default='/api/lost_child/search', max_length=100),
        ),
        migrations.AddField(
            model_name='mlserviceconfig',
            name='name',
            field=models.CharField(default='Primary ML Service', max_length=100),
        ),
        migrations.AddField(
            model_name='mlserviceconfig',
            name='severity_path',
            field=models.CharField(default='/api/severity/predict', max_length=100),
        ),
        migrations.AddField(
            model_name='mlserviceconfig',
            name='violence_frame_path',
            field=models.CharField(default='/api/violence/detect_frame', max_length=100),
        ),
        migrations.AddField(
            model_name='mlserviceconfig',
            name='violence_path',
            field=models.CharField(default='/api/violence/detect', max_length=100),
        ),
        migrations.AlterField(
            model_name='mlserviceconfig',
            name='base_url',
            field=models.CharField(help_text='http://localhost:8001', max_length=255, verbose_name='ML Service Base URL'),
        ),
    ]
